export default {
    // main section
    // html
    'Goroxels': 'Goroxels',
    'CHAT': 'CHAT',
    'login to chat': 'login to chat',
    'template': 'template',
    'template url': 'template url',
    'template opacity': 'template opacity',
    'settings': 'settings',
    'game settings': 'game settings',
    'open window': 'open window',
    'account settings': 'account settings',
    'toolbinds settings': 'toolbinds settings',
    'ui settings': 'ui settings',
    'tools': 'tools',
    'online': 'online',
    'Send alerts': 'Send alerts',
    // js and others
    // tools subsection
    'clicker': 'clicker',
    'protector': 'protector',
    'alt protector': 'alt protector',
    'mover': 'mover',
    'floodfill': 'floodfill',
    'pipette': 'pipette',
    'alt pipette': 'alt pipette',
    'coords to chat': 'coords to chat',
    'pixel info': 'pixel info',
    'swap colors': 'swap colors',
    'left color': 'left color',
    'right color': 'right color',
    'toggle chat': 'toggle chat',
    'toggle menu': 'toggle menu',
    'toggle everything': 'toggle everything',
    'ctrlZ': 'ctrlZ',
    'grid': 'grid',
    'paste': 'paste',
    'template 0/N opaq': 'template 0/N opaq',
    'template 1/N opaq': 'template 1/N opaq',
    'square': 'square',
    '+brush size': '+brush size',
    '-brush size': '-brush size',
    'copy': 'copy',
    // end tools subsection
    'colors size': 'colors size',
    'palette width': 'palette width',
    'hide emojis': 'hide emojis',
    'emoji list': 'emoji list',
    'super secret button': 'super secret button',
    'show placed pixels': 'show placed pixels',
    'more emojis!': 'more emojis!',
    'show protected': 'show protected',
    'brush size': 'brush size',
    'max saved pixels': 'max saved pixels',
    'disable chat colors': 'disable chat colors',
    'chat messages limit': 'chat messages limit',
    'light grid': 'light grid',
    'enable grid': 'enable grid',
    'Case insensitive, 0/o i/l are same': 'Case insensitive, 0/o i/l are same',
    'Can\'t recognize?': 'Can\'t recognize?',
    'Captcha': 'Captcha',
    'search users': 'search users',
    'OR': 'OR',
    'banned?': 'banned?',
    'Goroxels is a multiplayer pixel game with no cooldown! (ok, almost)': 'Goroxels is a multiplayer pixel game with no cooldown! (ok, almost)',
    'There are so many tools for make drawing more comfortable!': 'There are so many tools for make drawing more comfortable!',
    'Any Guest of this site can draw, but to get some features (ability to chat with other players, more lower cooldown) you should be registered.': 'Any Guest of this site can draw, but to get some features (ability to chat with other players, more lower cooldown) you should be registered.',
    'Very simple: you should pick color you need from palette (with pipette or just click) and place the pixel on canvas with LMB.': 'Very simple: you should pick color you need from palette (with pipette or just click) and place the pixel on canvas with LMB.',
    'You can use in-game clicker to place more pixels at time.': 'You can use in-game clicker to place more pixels at time.',
    'Tools Goroxels have:': 'Tools Goroxels have:',
    'Clicker. You need to hold whitespace and move your mouse to use it.': 'Clicker. You need to hold whitespace and move your mouse to use it.',
    'In the future, it will stop to place pixels continuously to protect arts.': 'In the future, it will stop to place pixels continuously to protect arts.',
    'Registred and Trusted users can draw with more lower cooldown than Guest users.': 'Registred and Trusted users can draw with more lower cooldown than Guest users.',
    'You can quickly switch colors with [A] (previous color) и [S] (next color).': 'You can quickly switch colors with [A] (previous color) и [S] (next color).',
    'You can also pick color from the canvas using pipette with [C].': 'You can also pick color from the canvas using pipette with [C].',
    'And so, brush size can be controlled (unavailable to Guests) with help of [ ] keys.': 'And so, brush size can be controlled (unavailable to Guests) with help of [ ] keys.',
    'Straight lines are so important to make art. You can use them with help of your mouse and [Shift].': 'Straight lines are so important to make art. You can use them with help of your mouse and [Shift].',
    'And so, the most important tool - Floodfill. [F], it helps so much to fill area with color. Hold this key for preview. If everything suits you, click [F] again.': 'And so, the most important tool - Floodfill. [F], it helps so much to fill area with color. Hold this key for preview. If everything suits you, click [F] again.',
    'If you need to quickly reset color(s), click RMB on canvas.': 'If you need to quickly reset color(s), click RMB on canvas.',
    'For grid use [G].': 'For grid use [G].',
    'If you placed the pixel(s) wrong, use [Z] (you can switch it to Ctrl+Z) for rollback. Keep holding Z to rollback all your wrong pixels (you can change amount of max saved pixels with Settings).': 'If you placed the pixel(s) wrong, use [Z] (you can switch it to Ctrl+Z) for rollback. Keep holding Z to rollback all your wrong pixels (you can change amount of max saved pixels with Settings)',
    'Multicolour support - brush can draw with a "chess style".': 'Multicolour support - brush can draw with a "chess style".',
    'Second color can be picked with [Alt+C]. If you picked colors in a wrong order, it is not a big problem - press [X] to reverse it.': 'Second color can be picked with [Alt+C]. If you picked colors in a wrong order, it is not a big problem - press [X] to reverse it.',
	'Hide a upper menu with [L], hide the chat with [K], and hide all an UI: [;].': 'Hide a upper menu with [L], hide the chat with [K], and hide all an UI: [;].',
	'You can paste your picture on the canvas using [Ctrl+V] (only for Registered users); maybe in the future this tool can only be used by Moderators.': 'You can paste your picture on the canvas using [Ctrl+V] (only for Registered users); maybe in the future this tool can only be used by Moderators.',
	'Click [U] to send coords to the chat. Coords in the chat are able to click.': 'Click [U] to send coords to the chat. Coords in the chat are able to click.',
	'Template can be managed with opacity switching tools [O] (your opacity (X) to 0) or from your opacity (X) to max opacity [P].': 'Template can be managed with opacity switching tools [O] (your opacity to 0) or from your opacity to max opacity [P].',
	'Other tools are tools for testing or can be only used by Moderators.': 'Other tools are tools for testing or can be only used by Moderators.',
	'Yes, in the Goroxels you can draw by following template! Put image on the canvas with "image URL".': 'Yes, in the Goroxels you can draw by following template! Put image on the canvas with "image URL".',
	'When loading a picture, there are can be some troubles. I reccomend to put your picture on <a href="//imgur.com">imgur.com</a>.': 'When loading a picture, there are can be some troubles. I reccomend to put your picture on <a href="//imgur.com">imgur.com</a>.',
	'You can change coordinates by yourself (X and Y), or with help of a dragging (hold [Ctrl]).': 'You can change coordinates by yourself (X and Y), or with help of a dragging (hold [Ctrl]).',
	'Convert images to the Goroxels palette with <a href="/convert">Converter</a>. You can also convert image and draw, using a pattern convert!': 'Convert images to the Goroxels palette with <a href="/convert">Converter</a>. You can also convert image and draw, using a pattern convert!',
	'Recommendations: first, convert to the palette, copy converted image and paste it in the pattern converter. When it ready, click "upload on imgur" and copy link you get to the "image URL". Patterns will make your drawing process more relaxing and enjoyable!': 'Recommendations: first, convert to the palette, copy converted image and paste it in the pattern converter. When it ready, click "upload on imgur" and copy link you get to the "image URL". Patterns will make your drawing process more relaxing and enjoyable!',
	'If url is red,  image you picked is so big. Try to cut your image with parts.': 'If url is red, image you picked is so big. Try to cut your image with parts.',
	
    // converter section
    // html
    'Convert!': 'Convert!',
    'Into palette': 'Into palette',
    'GO!': 'GO!',
    'Dithering': 'Dithering',
    'None': 'None',
    'Floyd-Steinberg': 'Floyd-Steinberg',
    'Stuсki': 'Stuсki',
    'Chess': 'Chess',
    'Ordered (matrix)': 'Ordered (matrix)',
    'Threshold': 'Threshold',
    'Matrix size': 'Matrix size',
    'Darken': 'Darken',
    'Lighten': 'Lighten',
    'Balance': 'Balance',
    'Color function for ΔE': 'Color function for ΔE',
    'RGB + luminance [very fast and dirty]': 'RGB + luminance [very fast and dirty]',
    'ciede2000 [slow and accurate]': 'ciede2000 [slow and accurate]',
    'CMC I:c [weird and slow]': 'CMC I:c [weird and slow]',
    'Euclidian + color values [fast and dirty]': 'Euclidian + color values [fast and dirty]',
    'brightness tune': 'brightness tune',
    'reset': 'reset',
    'constrast tune': 'constrast tune',
    'resize preview automatically': 'resize preview automatically',
    'serpentine (slightly suppresses dithering artefacts)': 'serpentine (slightly suppresses dithering artefacts)',
    'Into patterns': 'Into patterns',
    'Choose a palette': 'Choose a palette',
    // js and others
    'Image is loaded, but pixels can not be gotten. Try to load it on Imgur or download->upload from file': 'Image is loaded, but pixels can not be gotten. Try to load it on Imgur or download->upload from file',
    '[clipboard]': '[clipboard]',
    'Choose a image!': 'Choose a image!',
    'Invalid link!': 'Invalid link!',
    'Done in': 'Done in', //: Done in TIME ms
    'ms.': 'ms.', // milliseconds
    's.': 's.', // seconds
    'Unknown image loading error. Maybe CORS, so try to upload on Imgur': 'Unknown image loading error. Maybe CORS, so try to upload on Imgur',
    'If your image is big, go make a tea and watch Doctor Who': 'If your image is big, go make a tea and watch Doctor Who',
    'Final image size:': 'Final image size:',
    'Upload on imgur!': 'Upload on imgur!',
    'Imgur upload failed, try upload manually and add this to a link:': 'Imgur upload failed, try upload manually',
    'Failed to load game palettes!': 'Failed to load game palettes!',
    'URL/file/clipboard': 'URL/file/clipboard',

    // admin section
    // html
    'Backup Viewer': 'Backup Viewer',
    'SELECT CANVAS': 'SELECT CANVAS',
    'SELECT DAY': 'SELECT DAY',
    'SELECT TIME': 'SELECT TIME',
    'rollback': 'rollback',
    'Show chunk grid': 'Show chunk grid',
    'Crop chunks from': 'Crop chunks from',
    'to': 'to',
    'Crop rollback too': 'Crop rollback too',
    'IP Actions': 'IP Actions',
    'Blacklist': 'Blacklist',
	'Whitelist': 'Whitelist',
    'UnBlackist': 'UnBlackist',
    'UnWhitelist': 'UnWhitelist',
    'send': 'send',
    'set captchaEnabled state': 'set captchaEnabled state',
    'set': 'set',
    'set afterJoinDelay value': 'set afterJoinDelay value',
    'Canvas Actions': 'Canvas Actions',
    'Canvas': 'Canvas',
    'DO': 'DO',
    'wipe': 'wipe',
    'enlarge': 'enlarge',
    'top': 'top',
    'right': 'right',
    'bottom': 'bottom',
    'left': 'left',
    // js and others TODO
}