export default {
    // main section
    // html
    'Goroxels': 'Goroxels',
    'CHAT': 'CHAT',
    'login to chat': 'login to chat',
    'template': 'template',
    'template url': 'template url',
    'template opacity': 'template opacity',
    'settings': 'settings',
    'game settings': 'game settings',
    'open window': 'open window',
    'account settings': 'account settings',
    'change name': 'change name',
    'logout': 'logout',
    'toolbinds settings': 'toolbinds settings',
    'ui settings': 'ui settings',
    'tools': 'tools',
    'online': 'online',
    'Send alerts': 'Send alerts',
    // js and others
    // tools subsection
    'clicker': 'clicker',
    'protector': 'protector',
    'alt protector': 'alt protector',
    'mover': 'mover',
    'floodfill': 'floodfill',
    'pipette': 'pipette',
    'alt pipette': 'alt pipette',
    'coords to chat': 'coords to chat',
    'pixel info': 'pixel info',
    'swap colors': 'swap colors',
    'left color': 'left color',
    'right color': 'right color',
    'toggle chat': 'toggle chat',
    'toggle menu': 'toggle menu',
    'toggle everything': 'toggle everything',
    'ctrlZ': 'ctrlZ',
    'grid': 'grid',
    'paste': 'paste',
    'template 0/N opaq': 'template 0/N opaq',
    'template 1/N opaq': 'template 1/N opaq',
    'square': 'square',
    '+brush size': '+brush size',
    '-brush size': '-brush size',
    'copy': 'copy',
    // end tools subsection
    'colors size': 'colors size',
    'palette width': 'palette width',
    'hide emojis': 'hide emojis',
    'emoji list': 'emoji list',
    'super secret button': 'super secret button',
    'show placed pixels': 'show placed pixels',
    'show patterns over the palette': 'show patterns over the palette',
    'more emojis!': 'more emojis!',
    'show protected': 'show protected',
    'brush size': 'brush size',
    'max saved pixels': 'max saved pixels',
    'disable chat colors': 'disable chat colors',
    'chat messages limit': 'chat messages limit',
    'light grid': 'light grid',
    'enable grid': 'enable grid',
    'draw line length': 'draw line length',
    'Case insensitive, 0/o i/l are same': 'Case insensitive, 0/o i/l are same',
    'Can\'t recognize?': 'Can\'t recognize?',
    'Captcha': 'Captcha',
    'search users': 'search users',
    'OR': 'OR',
    'banned?': 'banned?',
    'convert image into palette': 'convert image into palette',
    'save canvas': 'save canvas',
    'intro.introHeader': 'Where am I?',
    // help
    'how to play?': 'How to play?',
    'tools': 'Tools',
    'intro.tools2header': 'Underground tools',
    'intro.desc': ' - this is like <b>Pixel Battle</b>, but better!!',
    'intro.desc2': 'Paint over the template or draw something unique! Cooldown is definitely less than a second (impressive)!',
    'intro.desc3': 'You can draw just like that. But if you register, you can paint even faster (and also it\'s a secret, but you can chat, use blocked tools and get +5 luck bonus)',
    'intro.howToPlayDecs': 'Choose a color at the bottom, click on the canvas - a pixel will appear where you clicked.<br>Just perfect for a conservative.<br> BUT. Why not take a peek at the next part..?👁️',
    'intro.toolsDecs': 'To make life easier and grass greener, we did some weird stuff:<br><i>P.S all keys can be reassigned in settings</i>',
    'intro.toolsClicker': '<b>Clicker</b><br>YES, it clicks. No, it won\'t draw for you. Key: Spacebar<br>Available on mobile: yes',
    'intro.toolsAS': '<b>Back and Forth</b><br>You can quickly switch colors using [A] and [S]',
    'intro.toolC': '<b>Pipette</b><br>The game has a pipette [C]',
    'intro.brush': '<b>Brush</b><br>For those who behaved well, a bigger painting tool is available<br>Available on mobile: yes',
    'intro.line': '<b>Line</b><br>For straight dudes [Shift]',
    'intro.flood': '<b>Flood Fill</b><br>What are you filling me with! [F]<br>Available on mobile: yes',
    'intro.resetColors': '<b>Reset Selected Color</b><br>Can be done with a simple hand movement [Right click]',
    'intro.grid': '<b>Grid</b><br>turns on with [G]',
    'intro.ctrlZ': '<b>Gal, undo</b><br>You can even cancel pixels!! Key: [Z]<br>Saving limit is adjustable<br>Available on mobile: yes',
    'intro.tools2desc': 'These tools are additional, but they only make things cooler!!',
    'intro.toolsHiders': '<b>Remove Excess</b><br>You can remove stuff from the interface with separate keybindings. [K] hides the chat, [L] hides the top panel, and [;] hides everything at once',
    'intro.multicol': '<b>One Gray, One White</b><br>For advanced users, multicolor support has been added - this is when the brush draws with two colors at once, alternating between them.'+
        '<br>Why?<br>Because of dithering (when the image is intentionally distorted so as not to look shabby in the site\'s palette).<br>Often the image turns out with alternating colors, '+
        'and in order not to waste the last nerve cells - this thing was made; sit, draw with two at once.',
    'intro.multicol2': 'The second color can be selected by [RMB] on the color in the palette or with the help of the pipette brother - [Alt+C] on the canvas.',
    'intro.multicol3': "(oh no.. Mixed up the color order and nerves are on edge? Just press [X])",
    'intro.sendCoords': "<b>Coordinates in chat</b><br>You can send them by pressing [U]",
    'intro.templateTools': "<b>Template</b><br>has its own binds too! [O] and [P] instantly toggle its transparency.<br>You can also move the template by holding [Ctrl] and [LMB]",
    'intro.templateIntro': "Wanderer, you've come so far! Well, I'll share a secret...",
    'intro.templateDesc': "The principle is simple and, if it helps, approximately the same as on pxls.space. <br>You insert a direct link to the image in the URL field (top left), enter the necessary coordinates, and draw on top",
    'intro.templateDescConvert': "<b>But my image isn't in the palette</b><br>If you want it in the palette - go to <a href='/convert' target='_blank'>/convert</a>. Insert the image into the input field at the top.",
    'intro.templateDescReminder': "<b>BY THE WAY</b><br>You can draw just like in this video. Want to do the same? Go to <a href='/convert' target='_blank'>/convert</a> (convert to pattern -> [upload image to imgur])<br>"+
    "<i>P.S. Set the template opacity to maximum.</i><br>"+
    "<i>P.P.S. if the link is in red - you'll have to fill it in manually. Instructions: </i><a href='//vk.cc/cmGiuG' target='_blank'>vk.cc/cmGiuG</a>",
    'intro.authorHeader': 'author',
    'intro.authorText':'Authors - Goroh and Comrades',
    'intro.authorContacts': "<img src='./img/telegram.svg' style='vertical-align:middle;height:40px'> <a href='//t.me/antieden'>Telegram</a><br>"+
    "<img src='./img/discord-logo-circle.svg' style='vertical-align:middle;height:40px'> Goroh#0385<br>"+
    "<img src='./img/discord-logo-circle.svg' style='vertical-align:middle;height:40px'> <a href=\"//discord.gg/FeBMmwRUpA\">Game server</a>",
    // nsfw modal
    'WARNING': 'WARNING',
    'This canvas may contain illustrations, inappropriate for people under age of 18, including:': 'This canvas may contain illustrations, inappropriate for people under age of 18, including:',
    'Gore, furry, porn, hate, anime and all possible variations of these.': 'Gore, furry, porn, hate, anime and all possible variations of these.',
    'Are you 18 y.o. and fully understanding what are you doing?': 'Are you 18 y.o. and fully understanding what are you doing?',
    'I am 18 years old and I take responsibility for my psyche on myself': 'I am 18 years old and I take responsibility for my psyche on myself',	
    // converter section
    // html
    'Convert!': 'Convert!',
    'Into palette': 'Into palette',
    'GO!': 'GO!',
    'Dithering': 'Dithering',
    'None': 'None',
    'Floyd-Steinberg': 'Floyd-Steinberg',
    'Stuсki': 'Stuсki',
    'Chess': 'Chess',
    'Ordered (matrix)': 'Ordered (matrix)',
    'Threshold': 'Threshold',
    'Matrix size': 'Matrix size',
    'Darken': 'Darken',
    'Lighten': 'Lighten',
    'Balance': 'Balance',
    'Color function for ΔE': 'Color function for ΔE',
    'RGB + luminance [very fast and dirty]': 'RGB + luminance [very fast and dirty]',
    'ciede2000 [slow and accurate]': 'ciede2000 [slow and accurate]',
    'CMC I:c [weird and slow]': 'CMC I:c [weird and slow]',
    'Euclidian + color values [fast and dirty]': 'Euclidian + color values [fast and dirty]',
    'brightness tune': 'brightness tune',
    'reset': 'reset',
    'constrast tune': 'constrast tune',
    'resize preview automatically': 'resize preview automatically',
    'serpentine (slightly suppresses dithering artefacts)': 'serpentine (slightly suppresses dithering artefacts)',
    'Into patterns': 'Into patterns',
    'Choose a palette': 'Choose a palette',
    // js and others
    'Image is loaded, but pixels can not be gotten. Try to load it on Imgur or download->upload from file': 'Image is loaded, but pixels can not be gotten. Try to load it on Imgur or download->upload from file',
    '[clipboard]': '[clipboard]',
    'Choose a image!': 'Choose a image!',
    'Invalid link!': 'Invalid link!',
    'Done in': 'Done in', //: Done in TIME ms
    'ms.': 'ms.', // milliseconds
    's.': 's.', // seconds
    'Unknown image loading error. Maybe CORS, so try to upload on Imgur': 'Unknown image loading error. Maybe CORS, so try to upload on Imgur',
    'If your image is big, go make a tea and watch Doctor Who': 'If your image is big, go make a tea and watch Doctor Who',
    'Final image size:': 'Final image size:',
    'Upload on imgur!': 'Upload on imgur!',
    'copy_canvas_btn': 'copy to Clipboard',
    'download_canvas_btn': 'download',
    'Imgur upload failed, try upload manually': 'Imgur upload failed, try upload manually',
    'insert_link_here': 'insert link here',
    'Failed to load game palettes!': 'Failed to load game palettes!',
    'URL/file/clipboard': 'URL/file/clipboard',

    // admin section
    // html
    'Backup Viewer': 'Backup Viewer',
    'SELECT CANVAS': 'SELECT CANVAS',
    'SELECT DAY': 'SELECT DAY',
    'SELECT TIME': 'SELECT TIME',
    'rollback': 'rollback',
    'Show chunk grid': 'Show chunk grid',
    'Crop chunks from': 'Crop chunks from',
    'to': 'to',
    'Crop rollback too': 'Crop rollback too',
    'IP Actions': 'IP Actions',
    'Blacklist': 'Blacklist',
	'Whitelist': 'Whitelist',
    'UnBlackist': 'UnBlackist',
    'UnWhitelist': 'UnWhitelist',
    'send': 'send',
    'set captchaEnabled state': 'set captchaEnabled state',
    'set': 'set',
    'set afterJoinDelay value': 'set afterJoinDelay value',
    'Canvas Actions': 'Canvas Actions',
    'Canvas': 'Canvas',
    'DO': 'DO',
    'wipe': 'wipe',
    'enlarge': 'enlarge',
    'top': 'top',
    'right': 'right',
    'bottom': 'bottom',
    'left': 'left',
    // js and others TODO
    'LOG IN': 'LOG IN',
    
}