export default {
    // main section
    // html
    'Goroxels': 'Goroxels',
    'CHAT': 'CHAT',
    'login to chat': 'login to chat',
    'template': 'template',
    'template url': 'template url',
    'template opacity': 'template opacity',
    'settings': 'settings',
    'game settings': 'game settings',
    'open window': 'open window',
    'account settings': 'account settings',
    'toolbinds settings': 'toolbinds settings',
    'ui settings': 'ui settings',
    'tools': 'tools',
    'online': 'online',
    'Send alerts': 'Send alerts',
    // js and others
    'change_name': 'Change nickname',
    'role': 'Role',
    'delete_account': 'Delete account',

    // converter section
    // html
    'Convert!': 'Convert!',
    'Into palette': 'Into palette',
    'GO!': 'GO!',
    'Dithering': 'Dithering',
    'None': 'None',
    'Floyd-Steinberg': 'Floyd-Steinberg',
    'Stuсki': 'Stuсki',
    'Chess': 'Chess',
    'Ordered (matrix)': 'Ordered (matrix)',
    'Threshold': 'Threshold',
    'Matrix size': 'Matrix size',
    'Darken': 'Darken',
    'Lighten': 'Lighten',
    'Balance': 'Balance',
    'Color function for ΔE': 'Color function for ΔE',
    'RGB + luminance [very fast and dirty]': 'RGB + luminance [very fast and dirty]',
    'ciede2000 [slow and accurate]': 'ciede2000 [slow and accurate]',
    'CMC I:c [weird and slow]': 'CMC I:c [weird and slow]',
    'Euclidian + color values [fast and dirty]': 'Euclidian + color values [fast and dirty]',
    'brightness tune': 'brightness tune',
    'reset': 'reset',
    'constrast tune': 'constrast tune',
    'resize preview automatically': 'resize preview automatically',
    'serpentine (slightly suppresses dithering artefacts)': 'serpentine (slightly suppresses dithering artefacts)',
    'Into patterns': 'Into patterns',
    'Choose a palette': 'Choose a palette',
    // js and others
    'Image is loaded, but pixels can not be gotten. Try to load it on Imgur or download->upload from file': 'Image is loaded, but pixels can not be gotten. Try to load it on Imgur or download->upload from file',
    '[clipboard]': '[clipboard]',
    'Choose a image!': 'Choose a image!',
    'Invalid link!': 'Invalid link!',
    'Done in': 'Done in', //: Done in TIME ms
    'ms.': 'ms.', // milliseconds
    's.': 's.', // seconds
    'Unknown image loading error. Maybe CORS, so try to upload on Imgur': 'Unknown image loading error. Maybe CORS, so try to upload on Imgur',
    'If your image is big, go make a tea and watch Doctor Who': 'If your image is big, go make a tea and watch Doctor Who',
    'Final image size:': 'Final image size:',
    'Upload on imgur!': 'Upload on imgur!',
    'Imgur upload failed, try upload manually and add this to a link:': 'Imgur upload failed, try upload manually',
    'Failed to load game palettes!': 'Failed to load game palettes!',
    'URL/file/clipboard': 'URL/file/clipboard',

    // admin section
    // html
    'Backup Viewer': 'Backup Viewer',
    'SELECT CANVAS': 'SELECT CANVAS',
    'SELECT DAY': 'SELECT DAY',
    'SELECT TIME': 'SELECT TIME',
    'rollback': 'rollback',
    'Show chunk grid': 'Show chunk grid',
    'Crop chunks from': 'Crop chunks from',
    'to': 'to',
    'Crop rollback too': 'Crop rollback too',
    'IP Actions': 'IP Actions',
    'Blacklist': 'Blacklist',
    'UnBlackist': 'UnBlackist',
    'UnWhitelist': 'UnWhitelist',
    'send': 'send',
    'set captchaEnabled state': 'set captchaEnabled state',
    'set': 'set',
    'set afterJoinDelay value': 'set afterJoinDelay value',
    'Canvas Actions': 'Canvas Actions',
    'Canvas': 'Canvas',
    'DO': 'DO',
    'wipe': 'wipe',
    'enlarge': 'enlarge',
    'top': 'top',
    'right': 'right',
    'bottom': 'bottom',
    'left': 'left',
    // js and others TODO
}